### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by AHTB** [siputra12/fakecall#10]
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/fakecall/call.php:59
Stack trace:
#0 /root/fakecall/call.php(100): prankCall->loop()
#1 /root/fakecall/call.php(110): prankCall->run()
#2 {main}
  thrown in /root/fakecall/call.php on line 59

**Comment by AlexTheDuck** [comment]
you dont know php dont you

**Comment by saidako38** [comment]
yas

في الخميس، ١٦ سبتمبر ٢٠٢١ ١:٠٢ م AlexTheDuck ***@***.***> كتب:
