### ISSUE TITLE
new issues

### ISSUE THREAD

**Issue by AHTB** [siputra12/fakecall#2]
hi this is the issues any help

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/fakecall/call.php:59
Stack trace:
#0 /root/fakecall/call.php(100): prankCall->loop('2')
#1 /root/fakecall/call.php(110): prankCall->run()
#2 {main}
  thrown in /root/fakecall/call.php on line 59

**Comment by MohammadRaad** [comment]
just you need to install php_curl using the following command:

> apt-get install php-curl

Or if you're using the old PHP5

>  apt-get install php5-curl

or

>  apt-get install php5.6-curl

 @AHTB

**Comment by edwardsaltbae** [comment]
may i know available in which country?

**Comment by ValentinNikolaev** [comment]
@AHTB check https://github.com/ValentinNikolaev/fakecall

**Comment by MoAbdullahConQ** [comment]
no

**Comment by saidako38** [comment]
انتو مين?

في الخميس، ٤ أبريل ٢٠٢٤ ٢:٠٠ م MoAbdullahConQ ***@***.***>
كتب:
