### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by nawafphp** [siputra12/fakecall#7]
Hello, how you doing? 
there is problem
https://prnt.sc/w4fqoy

**Comment by human-bieng** [comment]
apt get install php-common php-curl -y

**Comment by nawafphp** [comment]
> apt get install php-common php-curl -y

It isn't work.
https://prnt.sc/w54t5o
nothing happend after I sent it.

Thanks BTW.

**Comment by human-bieng** [comment]
Hi Nawaf you welcome
It doesnt work with me too
I tried two repositories & same issue

**Comment by elamrawi** [comment]
how it work by cmd in windows ?

**Comment by ValentinNikolaev** [comment]
@elamrawi @nawafphp check my fork - https://github.com/ValentinNikolaev/fakecall

**Comment by nacer44** [comment]
Hello, how you doing?
there is problem
PHP Fatal error:  Uncaught Error: Call to undefined function abcdefghijklmnopqrstuvwxyz1234567890() in /home/kali/fakecall/call.php:82
Stack trace:
#0 /home/kali/fakecall/call.php(22): prankCall->randStr()
#1 /home/kali/fakecall/call.php(102): prankCall->ekse()
#2 /home/kali/fakecall/call.php(110): prankCall->run()
#3 {main}
  thrown in /home/kali/fakecall/call.php on line 82
